### ISSUE TITLE
制限時間を過ぎた際に配列外参照で落ちるバグ

### ISSUE THREAD

**Issue by iwashiira** [KashiPrg/DeepL_PDF_Translator#1]
ありがたくこっそり使わせていただいていたのですが、バグを発見したので報告します。

タイトルの通りですが、具体的には**deeplmanager.py**の147, 148行目と**pdftranslator.p**yの465行目にかけての処理において**translated**に渡されるリストのサイズが**paragraphs**と比べて一つ分小さくなってしまうがゆえに、**pdftranslator.py**の482行目からのfor文のなかで`i`が最大値を取った際に`tl_processed[i]`への参照が配列外参照となってプログラムが落ちるというものです。

この、リストtranslatedのサイズが一つ小さくなってしまう原因ですが、リストの最後が空文字列な状態で`("\n".join(リスト)).splitlines()`を行うと、文字列ができる際に末尾が`"\n"`の文字列となるので、splitlines()でリストに戻すときに`"\n"`の後ろに空文字列があるとは認識されないからです。
例えば`("\n".join(["", "", ""])).splitlines()`は`["", "", ""] ➡ "\n\n" ➡ ["", ""]`となります。

対策としては`"*"`などの空文字列でない文字列にするか、空文字列の個数を一つ増やすとよいと思います。

後、今回このバグに気づいたのには、翻訳元の文章に`[...]`が存在しており引用符の中だったので無理に翻訳もされず、**deeplmanager.py**の136行目でbreakできなかったという経緯があります。これについては、制限時間を過ぎたelseの冒頭に次のようなパッチをあてていますがどうでしょうか。

`if (re.search((r"\[\.\.\.\]", text) and re.search(r"\[\.\.\.\]", translated)): break`

**Comment by KashiPrg** [comment]
少々立て込んでいて反応できませんでした。
非常に詳しく調べていただいてありがとうございます！
もしもコメントがバグチェックの助けになったのなら、これがコメントを付けていて初めて役に立ったケースになります……。
ご指摘の箇所を直してみますね。

**Comment by KashiPrg** [comment]
ただいま修正版をリリースしました。
とても的確なご指摘でしたので、修正すべき場所がはっきりしていてスムーズにバグ修正できました。ありがとうございます。

今回は、翻訳失敗時のメッセージをその時翻訳しようとした最初の段落にしか表示せず、残りの段落には空文字列しか表示しない仕様だったために問題が発生したので、どこで失敗したのかをわかりやすくするためにも、翻訳に失敗したときに扱っていた全ての段落に失敗時のメッセージを表示するようにしました。

原文に`[...]`が存在した場合に翻訳失敗扱いになってしまう問題については、ご指摘のとおりに修正しました。

また、ChromeやEdgeでデバッグしていたときに、翻訳先言語の選択処理が速すぎて失敗するという現象を確認しましたので、その点も修正しました。
なぜかFireFoxでは、ブラウザに起因するエラーがほとんど発生しません。

もしよろしければ、問題なく動作することをご確認いただければ幸いです。
動作を確認していただくか、一定期間が経過した後にこのIssueをCloseしたいと思います。

**Comment by iwashiira** [comment]
確認しました。大丈夫そうです。

コメントとても分かりやすくて助かりました。

**Comment by KashiPrg** [comment]
こちらこそ大変助かりました。ありがとうございます。
それではCloseさせていただきます。
